SubsetTypesERR.dfy(11:11-11:11): Error: value of expression (of type 'array<Person>') is not known to be an instance of type 'array<Person?>'
SubsetTypesERR.dfy(13:11-13:11): Error: value of expression (of type 'array<Person>') is not known to be an instance of type 'array<Person?>'
SubsetTypesERR.dfy(15:11-15:11): Error: value of expression (of type 'array<Person>') is not known to be an instance of type 'array<Person?>'
SubsetTypesERR.dfy(17:11-17:11): Error: value of expression (of type 'array<Person>') is not known to be an instance of type 'array<Person?>'
SubsetTypesERR.dfy(23:11-23:11): Error: value of expression (of type 'array<Person?>') is not known to be an instance of type 'array<Person>'
SubsetTypesERR.dfy(25:11-25:11): Error: value of expression (of type 'array<Person?>') is not known to be an instance of type 'array<Person>'
SubsetTypesERR.dfy(27:11-27:11): Error: value of expression (of type 'array<Person?>') is not known to be an instance of type 'array<Person>'
SubsetTypesERR.dfy(29:11-29:11): Error: value of expression (of type 'array<Person?>') is not known to be an instance of type 'array<Person>'
SubsetTypesERR.dfy(37:11-37:11): Error: value of expression (of type 'array<Person>') is not known to be an instance of type 'array<Person?>'
SubsetTypesERR.dfy(39:11-39:11): Error: value of expression (of type 'array<Person?>') is not known to be an instance of type 'array<Person>'
SubsetTypesERR.dfy(42:11-42:11): Error: value of expression (of type 'array<Person?>') is not known to be an instance of type 'array<Person>'
SubsetTypesERR.dfy(44:11-44:11): Error: value of expression (of type 'array<Person>') is not known to be an instance of type 'array<Person?>'
SubsetTypesERR.dfy(46:11-46:11): Error: value of expression (of type 'array<Person?>') is not known to be an instance of type 'array<Person>'
SubsetTypesERR.dfy(57:11-57:11): Error: value of expression (of type 'Cell<Person?>') is not known to be an instance of type 'Cell<Person>'
SubsetTypesERR.dfy(59:11-59:11): Error: value of expression (of type 'Cell<Person>') is not known to be an instance of type 'Cell<Person?>'
SubsetTypesERR.dfy(63:11-63:11): Error: value of expression (of type 'Cell<Person>') is not known to be an instance of type 'Cell<Person?>'
SubsetTypesERR.dfy(65:11-65:11): Error: value of expression (of type 'Cell<Person?>') is not known to be an instance of type 'Cell<Person>'

Dafny program verifier finished with 0 verified, 17 errors
